env:
  - CGO_ENABLED=0

builds:
  -
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - '-s -w -X main.Version={{.Version}} -X main.VersionPrerelease= '
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - cmd: gpg
    args: ["-u", "ops@exoscale.ch", "--detach-sign", "${artifact}"]
    artifacts: all

release:
   draft: true
   github:
     owner: exoscale
     name: packer-plugin-exoscale

changelog:
  skip: true
