---
name: CI

on:
  pull_request:  # no need for 'push'; all pushes (to master) are PR-ed
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.mdx'
    tags-ignore:
      - 'v*'  # Don't run CI tests on release tags

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Checkout go.mk
        run: make go.mk
      - uses: ./go.mk/.github/actions/setup

      - uses: ./go.mk/.github/actions/pre-check

      - name: Build
        run: make build
      - name: Unit tests
        run: make test-verbose
      - name: Acceptance tests
        run: |
          make test-acc
          cd /tmp/packer-plugin-test && md5sum -c *.md5sum
        env:
          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
